name: Build & Release Lite ZIP

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to delete releases and upload assets.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v3

      - name: Delete previous release (if exists)
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest-lite
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create plugin zip with exact files only
        run: |
          mkdir -p build/eventkoi-lite

          cp -r includes build/eventkoi-lite/
          cp -r languages build/eventkoi-lite/

          if [ -d scripts/backend/build ]; then
            mkdir -p build/eventkoi-lite/scripts/backend
            cp -r scripts/backend/build build/eventkoi-lite/scripts/backend/
          fi

          if [ -d scripts/frontend/build ]; then
            mkdir -p build/eventkoi-lite/scripts/frontend
            cp -r scripts/frontend/build build/eventkoi-lite/scripts/frontend/
          fi

          cp -r templates build/eventkoi-lite/
          cp -r vendor-prefixed build/eventkoi-lite/

          cp autoload.php composer.json eventkoi-lite.php license.txt build/eventkoi-lite/

          cd build
          zip -qr eventkoi-lite.zip eventkoi-lite

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Latest Lite Release"
          tag_name: latest-lite
          files: build/eventkoi-lite.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Supabase Storage
        run: |
          curl -X PUT "${SUPABASE_URL}/storage/v1/object/eventkoi-lite/eventkoi-lite.zip" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE}" \
            -H "Content-Type: application/zip" \
            --data-binary @build/eventkoi-lite.zip
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
